#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""The six satellite signal icons (0 to 5 bars), as MeshSat Android's status-bar icons
(res/drawable/ic_stat_iridium_N.xml): an Iridium satellite top left, five bars rising to the
right, the bars above the signal at 30 % opacity. Written as symbolic SVGs, so a panel, a
notification or a tray recolours them for its own background.

    tools/make-signal-icons.py [out-dir]    default: app/meshsat/icons/hicolor/scalable/status
"""
import os
import sys

# The satellite: body, two panels, the struts and the antenna, turned 45 degrees about (8, 8).
SATELLITE = ("M6.3,6.3H9.7V9.7H6.3Z",
             "M1.2,6.9H5.4V9.1H1.2Z M10.6,6.9H14.8V9.1H10.6Z",
             "M5.4,7.7H6.3V8.3H5.4Z M9.7,7.7H10.6V8.3H9.7Z M7.7,3.6H8.3V6.3H7.7Z")
# The bars, shortest first.
BARS = ("M13.0,19.5H14.6V22H13.0Z", "M15.2,18.0H16.8V22H15.2Z", "M17.4,16.5H19.0V22H17.4Z", "M19.6,15.0H21.2V22H19.6Z", "M21.8,13.5H23.4V22H21.8Z")


def icon(bars: int) -> str:
    lines = ['<?xml version="1.0" encoding="UTF-8"?>',
             f'<!-- MeshSat: Iridium signal, {bars} of 5 bars. Generated by tools/make-signal-icons.py. -->',
             '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24">',
             '  <g transform="rotate(-45 8 8)" fill="#2e3436">']
    lines += [f'    <path d="{d}"/>' for d in SATELLITE]
    lines.append("  </g>")
    for i, d in enumerate(BARS):
        opacity = "" if i < bars else ' opacity="0.3"'
        lines.append(f'  <path d="{d}" fill="#2e3436"{opacity}/>')
    lines.append("</svg>")
    return "\n".join(lines) + "\n"


def main() -> int:
    here = os.path.dirname(os.path.abspath(__file__))
    out = sys.argv[1] if len(sys.argv) > 1 else os.path.join(here, "..", "app", "meshsat", "icons", "hicolor", "scalable", "status")
    os.makedirs(out, exist_ok=True)
    for bars in range(6):
        path = os.path.join(out, f"meshsat-iridium-{bars}-symbolic.svg")
        with open(path, "w", encoding="utf-8") as handle:
            handle.write(icon(bars))
        print(os.path.normpath(path))
    return 0


if __name__ == "__main__":
    sys.exit(main())
